name: proyecto-tics

services:
  db:
    image: postgres:16-alpine
    container_name: tic-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bd_inventario
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rpa-service:
    image: lincolmvf/rpa-infotec-v1:latest
    container_name: rpa-service
    ports:
      - "3001:3001"
    restart: always

  backend-service:
    image: lincolmvf/backend-tic-s:latest
    #build: ./
    container_name: backend-service
    ports:
      - "3002:3002"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      rpa-service:
        condition: service_started
    restart: always

  frontend-service:
    image: lincolmvf/frontend-tic-s:latest
    #build: ../Frontend-Tic
    container_name: frontend-service
    ports:
      - "80:80"
    depends_on:
      - backend-service
    restart: always

volumes:
  db_data: