name: proyecto-tics

services:
  rpa-service:
    build: ../RPA_Curso_TIC-s
    container_name: rpa-service
    ports:
      - "3001:3001"
    restart: always

  backend-service:
    build: ../Backend-Tic
    container_name: backend-service
    ports:
      - "3002:3002"
    env_file:
      - .env
    depends_on:
      - rpa-service
    restart: always